name: deploy-book

on:
  push:
    branches:
      - master
      - main

env:
  BASE_URL: /${{ github.event.repository.name }}

jobs:
  deploy-book:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the book
        run: |
          jupyter book build --html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
